name: build-test
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
jobs:
  build-test:
    name: Build and Test
    strategy:
      matrix:
        go-version:
          - 1.12.x
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Create Database
        run: |
          sudo systemctl start mysql.service 
          mysql --user root --password root < db.sql
      - name: Build
        run: make
      - name: Test
        run: make test
